export const GET_USER_ACCOUNTS ="GET_USER_ACCOUNTS";
export const GET_USER_ACCOUNTS_SUCCESS ="GET_USER_ACCOUNTS_SUCCESS";
export const GET_USER_ACCOUNTS_ERROR ="GET_USER_ACCOUNTS_ERROR";

export const GET_ACCOUNT_DETAIL ="GET_ACCOUNT_DETAIL";

export const SET_CURRENT_ACCOUNT = "SET_CURRENT_ACCOUNT";

export const CREATE_ACCOUNT = "CREATE_ACCOUNT";
export const CREATE_ACCOUNT_SUCCESS = "CREATE_ACCOUNT_SUCCESS";
export const CREATE_ACCOUNT_ERROR = "CREATE_ACCOUNT_ERROR";

export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS";
export const DELETE_ACCOUNT_ERROR = "DELETE_ACCOUNT_ERROR";

export const GET_PUBLIC_ACCOUNTS ="GET_PUBLIC_ACCOUNTS";
export const GET_PUBLIC_ACCOUNTS_SUCCESS ="GET_PUBLIC_ACCOUNTS_SUCCESS";
export const GET_PUBLIC_ACCOUNTS_ERROR ="GET_PUBLIC_ACCOUNTS_ERROR";







