export const GET_USER_ACCOUNTS ="GET_USER_ACCOUNTS";
export const GET_USER_ACCOUNTS_SUCCESS ="GET_USER_ACCOUNTS_SUCCESS";
export const GET_USER_ACCOUNTS_ERROR ="GET_USER_ACCOUNTS_ERROR";

export const GET_ACCOUNT_DETAIL ="GET_ACCOUNT_DETAIL";

