export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";

export const OKTA_LOGIN = "OKTA_LOGIN";
export const OKTA_LOGIN_SUCCESS  = "OKTA_LOGIN_SUCCESS";
export const OKTA_LOGIN_ERROR  = "OKTA_LOGIN_ERROR";

export const GET_USERDATA_SUCCESS = " GET_USERDATA_SUCCESS";
export const GET_USERDATA_ERROR = " GET_USERDATA_ERROR";