export const CREATE_INVITATION = "CREATE_INVITATION";
export const CREATE_INVITATION_SUCCESS = "CREATE_INVITATION_SUCCESS";
export const CREATE_INVITATION_ERROR = "CREATE_INVITATION_ERROR";

export const GET_SOURCE_INVITES = "GET_SOURCE_INVITES";
export const GET_SOURCE_INVITES_SUCCESS = "GET_SOURCE_INVITES_SUCCESS";
export const GET_SOURCE_INVITES_ERROR = "GET_SOURCE_INVITES_ERROR";

export const GET_TARGET_INVITES = "GET_TARGET_INVITES";
export const GET_TARGET_INVITES_SUCCESS = "GET_TARGET_INVITES_SUCCESS";
export const GET_TARGET_INVITES_ERROR = "GET_TARGET_INVITES_ERROR";

export const GET_INVITE_COUNT = "GET_INVITE_COUNT";
export const GET_INVITE_COUNT_SUCESS = "GET_INVITE_COUNT_SUCESS";
export const GET_INVITE_COUNT_ERROR = "GET_INVITE_COUNT_ERROR";

export const CREATE_ACCOUNT_LINK = "CREATE_ACCOUNT_LINK";
export const CREATE_ACCOUNT_LINK_SUCCESS = "CREATE_ACCOUNT_LINK_SUCCESS";
export const CREATE_ACCOUNT_LINK_ERROR = "CREATE_ACCOUNT_LINK_ERROR";

export const ACCEPT_ACCOUNT_LINK = "ACCEPT_ACCOUNT_LINK";
export const ACCEPT_ACCOUNT_LINK_SUCCESS = "ACCEPT_ACCOUNT_LINK_SUCCESS";
export const ACCEPT_ACCOUNT_LINK_ERROR = "ACCEPT_ACCOUNT_LINK_ERROR";

export const REJECT_ACCOUNT_LINK = "REJECT_ACCOUNT_LINK";
export const REJECT_ACCOUNT_LINK_SUCCESS = "REJECT_ACCOUNT_LINK_SUCCESS";
export const REJECT_ACCOUNT_LINK_ERROR = "REJECT_ACCOUNT_LINK_ERROR";

export const GET_ACCOUNT_LINKS = "GET_ACCOUNT_LINKS";
export const GET_ACCOUNT_LINKS_SUCCESS = "GET_ACCOUNT_LINKS_SUCCESS";
export const GET_ACCOUNT_LINKS_ERROR = "GET_ACCOUNT_LINKS_ERROR";
