export const CREATE_INVITATION = "CREATE_INVITATION";
export const CREATE_INVITATION_SUCCESS = "CREATE_INVITATION_SUCCESS";
export const CREATE_INVITATION_ERROR = "CREATE_INVITATION_ERROR";

export const GET_SOURCE_INVITES = "GET_SOURCE_INVITES";
export const GET_SOURCE_INVITES_SUCCESS = "GET_SOURCE_INVITES_SUCCESS";
export const GET_SOURCE_INVITES_ERROR = "GET_SOURCE_INVITES_ERROR";

export const GET_TARGET_INVITES = "GET_TARGET_INVITES";
export const GET_TARGET_INVITES_SUCCESS = "GET_TARGET_INVITES_SUCCESS";
export const GET_TARGET_INVITES_ERROR = "GET_TARGET_INVITES_ERROR";
