export const CREATE_KYC_SCHEMA = "CREATE_KYC_SCHEMA";
export const CREATE_KYC_SCHEMA_SUCCESS = "CREATE_KYC_SCHEMA_SUCCESS";
export const CREATE_KYC_SCHEMA_ERROR = "CREATE_KYC_SCHEMA_ERROR";

export const UPDATE_KYC_SCHEMA = "UPDATE_KYC_SCHEMA";
export const UPDATE_KYC_SCHEMA_SUCCESS = "UPDATE_KYC_SCHEMA_SUCCESS";
export const UPDATE_KYC_SCHEMA_ERROR = "UPDATE_KYC_SCHEMA_ERROR";

export const DELETE_KYC_SCHEMA = "DELETE_KYC_SCHEMA";
export const DELETE_KYC_SCHEMA_SUCCESS = "DELETE_KYC_SCHEMA_SUCCESS";
export const DELETE_KYC_SCHEMA_ERROR = "DELETE_KYC_SCHEMA_ERROR";

export const GET_KYC_SCHEMAS = "GET_KYC_SCHEMAS";
export const GET_KYC_SCHEMAS_SUCCESS = "GET_KYC_SCHEMAS_SUCCESS";
export const GET_KYC_SCHEMAS_ERROR = "GET_KYC_SCHEMAS_ERROR";


export const CREATE_KYC_SCHEMA_DEFINITION = "CREATE_KYC_SCHEMA_DEFINITION";
export const CREATE_KYC_SCHEMA_DEFINITION_SUCCESS = "CREATE_KYC_SCHEMA_DEFINITION_SUCCESS";
export const CREATE_KYC_SCHEMA_DEFINITION_ERROR = "CREATE_KYC_SCHEMA_DEFINITION_ERROR";

export const UPDATE_KYC_SCHEMA_DEFINITION = "UPDATE_KYC_SCHEMA_DEFINITION";
export const UPDATE_KYC_SCHEMA_DEFINITION_SUCCESS = "UPDATE_KYC_SCHEMA_DEFINITION_SUCCESS";
export const UPDATE_KYC_SCHEMA_DEFINITION_ERROR = "UPDATE_KYC_SCHEMA_DEFINITION_ERROR";

export const GET_KYC_SCHEMA_DEFINITIONS = "GET_KYC_SCHEMA_DEFINITIONS";
export const GET_KYC_SCHEMA_DEFINITIONS_SUCCESS = "GET_KYC_SCHEMA_DEFINITIONS_SUCCESS";
export const GET_KYC_SCHEMA_DEFINITIONS_ERROR = "GET_KYC_SCHEMA_DEFINITIONS_ERROR";

// TODO move to KYC Constants
export const CREATE_KYC_SCHEMA_DEFINITION_OFFER = "CREATE_KYC_SCHEMA_DEFINITION_OFFER";
export const CREATE_KYC_SCHEMA_DEFINITION_OFFER_SUCCESS = "CREATE_KYC_SCHEMA_DEFINITION_OFFER_SUCCESS";
export const CREATE_KYC_SCHEMA_DEFINITION_OFFER_ERROR = "CREATE_KYC_SCHEMA_DEFINITION_OFFER_ERROR";

export const GET_KYC_CREDENTIALS_OFFERS = "GET_KYC_CREDENTIALS_OFFERS";
export const GET_KYC_CREDENTIALS_OFFERS_SUCCESS = "GET_KYC_CREDENTIALS_OFFERS_SUCCESS";
export const GET_KYC_CREDENTIALS_OFFERS_ERROR = "GET_KYC_CREDENTIALS_OFFERS_ERROR";