export const CREATE_KYC_SCHEMA = "CREATE_KYC_SCHEMA";
export const CREATE_KYC_SCHEMA_SUCCESS = "CREATE_KYC_SCHEMA_SUCCESS";
export const CREATE_KYC_SCHEMA_ERROR = "CREATE_KYC_SCHEMA_ERROR";

export const UPDATE_KYC_SCHEMA = "UPDATE_KYC_SCHEMA";
export const UPDATE_KYC_SCHEMA_SUCCESS = "UPDATE_KYC_SCHEMA_SUCCESS";
export const UPDATE_KYC_SCHEMA_ERROR = "UPDATE_KYC_SCHEMA_ERROR";

export const GET_KYC_SCHEMAS = "GET_KYC_SCHEMAS";
export const GET_KYC_SCHEMAS_SUCCESS = "GET_KYC_SCHEMAS_SUCCESS";
export const GET_KYC_SCHEMAS_ERROR = "GET_KYC_SCHEMAS_ERROR";